%% Publication-quality visualization of Function Encoder reconstructions
% Each sample is exported as a 2-by-3 figure:
%   Row 1: P true, P reconstruction, P error (reconstruction - true)
%   Row 2: f true, f reconstruction, f error (reconstruction - true)
%
% The .mat file generated by train_function_encoder_polar.ipynb stores
% fields in [sample, r, theta] order.

clearvars;
close all;
clc;

%% User settings
scriptDir = fileparts(mfilename('fullpath'));
matFile = fullfile( ...
    scriptDir, ...
    'out_polar_annulus_sno', ...
    'polar_v1', ...
    'fe_reconstruction_test', ...
    'fe_reconstruction_test.mat');

outputDir = fullfile(fileparts(matFile), 'matlab_figures');

% Leave empty to export every sample. Example: sampleIds = [1, 8, 20];
sampleIds = [20:30];

exportPDF = false;
exportPNG = false;
pngResolution = 600;

% true: display figures in MATLAB and keep them open after export.
% Select only a few samples to avoid opening too many figure windows.
showFigures = true;

% Full-width, journal-ready figure dimensions.
figureWidthCm = 18.3;
figureHeightCm = 9.3;

fontName = 'Times New Roman';
axisFontSize = 8;
titleFontSize = 9;
superTitleFontSize = 10;

%% Load and validate data
assert(isfile(matFile), 'MAT file not found: %s', matFile);
S = load(matFile);

requiredVariables = { ...
    'theta', 'radius', ...
    'P_true', 'P_recon', 'P_error', ...
    'f_true', 'f_recon', 'f_error', ...
    'P_relative_l2', 'f_relative_l2'};

for iVar = 1:numel(requiredVariables)
    name = requiredVariables{iVar};
    assert(isfield(S, name), 'Required variable "%s" is missing.', name);
end

assert(isequal(size(S.P_true), size(S.P_recon), size(S.P_error)), ...
    'P_true, P_recon and P_error must have identical sizes.');
assert(isequal(size(S.f_true), size(S.f_recon), size(S.f_error)), ...
    'f_true, f_recon and f_error must have identical sizes.');
assert(isequal(size(S.P_true), size(S.f_true)), ...
    'P and f arrays must have identical [sample, r, theta] sizes.');

theta = double(S.theta(:));
radius = double(S.radius(:));
nSamples = size(S.P_true, 1);

assert(size(S.P_true, 2) == numel(radius), ...
    'The radial dimension does not match radius.');
assert(size(S.P_true, 3) == numel(theta), ...
    'The angular dimension does not match theta.');
assert(numel(S.P_relative_l2) == nSamples, ...
    'P_relative_l2 length does not match the number of samples.');
assert(numel(S.f_relative_l2) == nSamples, ...
    'f_relative_l2 length does not match the number of samples.');

if isempty(sampleIds)
    sampleIds = 1:nSamples;
end

sampleIds = unique(sampleIds(:).', 'stable');
assert(all(sampleIds >= 1 & sampleIds <= nSamples & sampleIds == floor(sampleIds)), ...
    'sampleIds must contain integer indices in the range 1 to %d.', nSamples);

if ~exist(outputDir, 'dir')
    mkdir(outputDir);
end

fprintf('MAT file: %s\n', matFile);
fprintf('Samples in file: %d\n', nSamples);
fprintf('Samples selected for export: %d\n', numel(sampleIds));
fprintf('Output directory: %s\n', outputDir);

if showFigures && numel(sampleIds) > 12
    warning(['showFigures=true with %d samples will open many figure windows. ', ...
        'Set sampleIds to a smaller subset for interactive inspection.'], ...
        numel(sampleIds));
end

%% Draw and export each sample
divergingMap = publicationDivergingMap(256);
panelLabels = {'a', 'b', 'c', 'd', 'e', 'f'};

for iSample = 1:numel(sampleIds)
    sampleId = sampleIds(iSample);

    pTrue = double(squeeze(S.P_true(sampleId, :, :)));
    pRecon = double(squeeze(S.P_recon(sampleId, :, :)));
    pError = double(squeeze(S.P_error(sampleId, :, :)));

    fTrue = double(squeeze(S.f_true(sampleId, :, :)));
    fRecon = double(squeeze(S.f_recon(sampleId, :, :)));
    fError = double(squeeze(S.f_error(sampleId, :, :)));

    % True and reconstructed fields share an identical, zero-centred scale.
    % Error panels use their own zero-centred scale. No percentile clipping
    % is applied, so the complete numerical range remains visible.
    pFieldLimits = symmetricColorLimits(pTrue, pRecon);
    pErrorLimits = symmetricColorLimits(pError);
    fFieldLimits = symmetricColorLimits(fTrue, fRecon);
    fErrorLimits = symmetricColorLimits(fError);

    pRelativeError = double(S.P_relative_l2(sampleId));
    fRelativeError = double(S.f_relative_l2(sampleId));

    if showFigures
        figureVisibility = 'on';
    else
        figureVisibility = 'off';
    end

    fig = figure( ...
        'Color', 'w', ...
        'Units', 'centimeters', ...
        'Position', [2, 2, figureWidthCm, figureHeightCm], ...
        'PaperPositionMode', 'auto', ...
        'Visible', figureVisibility);

    layout = tiledlayout(fig, 2, 3, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact');

    ax1 = nexttile(layout, 1);
    drawFieldPanel(ax1, theta, radius, pTrue, pFieldLimits, ...
        '{\itP} true', panelLabels{1}, '{\itP}', divergingMap, ...
        fontName, axisFontSize, titleFontSize);

    ax2 = nexttile(layout, 2);
    drawFieldPanel(ax2, theta, radius, pRecon, pFieldLimits, ...
        '{\itP} reconstruction', panelLabels{2}, '{\itP}', divergingMap, ...
        fontName, axisFontSize, titleFontSize);

    ax3 = nexttile(layout, 3);
    drawFieldPanel(ax3, theta, radius, pError, pErrorLimits, ...
        '{\itP} error (recon. - true)', panelLabels{3}, '\Delta{\itP}', ...
        divergingMap, fontName, axisFontSize, titleFontSize);

    ax4 = nexttile(layout, 4);
    drawFieldPanel(ax4, theta, radius, fTrue, fFieldLimits, ...
        '{\itf} true', panelLabels{4}, '{\itf}', divergingMap, ...
        fontName, axisFontSize, titleFontSize);

    ax5 = nexttile(layout, 5);
    drawFieldPanel(ax5, theta, radius, fRecon, fFieldLimits, ...
        '{\itf} reconstruction', panelLabels{5}, '{\itf}', divergingMap, ...
        fontName, axisFontSize, titleFontSize);

    ax6 = nexttile(layout, 6);
    drawFieldPanel(ax6, theta, radius, fError, fErrorLimits, ...
        '{\itf} error (recon. - true)', panelLabels{6}, '\Delta{\itf}', ...
        divergingMap, fontName, axisFontSize, titleFontSize);

    % Avoid repeated y-axis labels while retaining readable tick marks.
    xlabel(ax1, '');
    xlabel(ax2, '');
    xlabel(ax3, '');
    ylabel(ax2, '');
    ylabel(ax3, '');
    ylabel(ax5, '');
    ylabel(ax6, '');

    figureTitle = sprintf( ...
        'Sample %d   |   P relative L_2 error = %.3e   |   f relative L_2 error = %.3e', ...
        sampleId, pRelativeError, fRelativeError);
    titleHandle = sgtitle(layout, figureTitle, ...
        'Interpreter', 'tex', ...
        'FontName', fontName, ...
        'FontSize', superTitleFontSize, ...
        'FontWeight', 'normal');
    titleHandle.Color = [0.08, 0.08, 0.08];

    baseName = sprintf('fe_reconstruction_sample_%04d', sampleId);

    if exportPDF
        exportgraphics(fig, fullfile(outputDir, [baseName, '.pdf']), ...
            'ContentType', 'vector', ...
            'BackgroundColor', 'white');
    end

    if exportPNG
        exportgraphics(fig, fullfile(outputDir, [baseName, '.png']), ...
            'Resolution', pngResolution, ...
            'BackgroundColor', 'white');
    end

    if showFigures
        drawnow;
    else
        close(fig);
    end

    if mod(iSample, 10) == 0 || iSample == numel(sampleIds)
        fprintf('Exported %d / %d samples.\n', iSample, numel(sampleIds));
    end
end

fprintf('Finished. Figures are in: %s\n', outputDir);

%% Local functions
function drawFieldPanel(ax, theta, radius, field, colorLimits, ...
    panelTitle, panelLabel, colorbarLabel, colorMap, ...
    fontName, axisFontSize, titleFontSize)

    imagesc(ax, theta, radius, field);
    set(ax, ...
        'YDir', 'normal', ...
        'FontName', fontName, ...
        'FontSize', axisFontSize, ...
        'LineWidth', 0.75, ...
        'TickDir', 'out', ...
        'TickLength', [0.015, 0.015], ...
        'Box', 'on', ...
        'Layer', 'top', ...
        'XColor', [0.12, 0.12, 0.12], ...
        'YColor', [0.12, 0.12, 0.12]);

    colormap(ax, colorMap);
    clim(ax, colorLimits);
    xlim(ax, [0, 2*pi]);
    ylim(ax, [radius(1), radius(end)]);
    xticks(ax, [0, pi, 2*pi]);
    xticklabels(ax, {'0', '\pi', '2\pi'});
    yticks(ax, linspace(radius(1), radius(end), 3));
    pbaspect(ax, [1.25, 1, 1]);

    xlabel(ax, '\theta (rad)', ...
        'Interpreter', 'tex', ...
        'FontName', fontName, ...
        'FontSize', axisFontSize + 1);
    ylabel(ax, 'r', ...
        'Interpreter', 'tex', ...
        'FontName', fontName, ...
        'FontSize', axisFontSize + 1);
    title(ax, panelTitle, ...
        'Interpreter', 'tex', ...
        'FontName', fontName, ...
        'FontSize', titleFontSize, ...
        'FontWeight', 'normal');

    cb = colorbar(ax, 'eastoutside');
    cb.FontName = fontName;
    cb.FontSize = axisFontSize - 1;
    cb.TickDirection = 'out';
    cb.LineWidth = 0.65;
    cb.Label.String = colorbarLabel;
    cb.Label.Interpreter = 'tex';
    cb.Label.FontName = fontName;
    cb.Label.FontSize = axisFontSize;

    text(ax, 0.02, 0.98, ['(', panelLabel, ')'], ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'top', ...
        'FontName', fontName, ...
        'FontSize', titleFontSize, ...
        'FontWeight', 'bold', ...
        'Color', [0.05, 0.05, 0.05], ...
        'BackgroundColor', 'white', ...
        'Margin', 1.0);
end


function limits = symmetricColorLimits(varargin)
    maxMagnitude = 0;

    for iField = 1:nargin
        values = varargin{iField};
        finiteValues = values(isfinite(values));
        if ~isempty(finiteValues)
            maxMagnitude = max(maxMagnitude, max(abs(finiteValues), [], 'all'));
        end
    end

    if ~isfinite(maxMagnitude) || maxMagnitude <= 0
        maxMagnitude = 1;
    end

    limits = [-maxMagnitude, maxMagnitude];
end


function colorMap = publicationDivergingMap(nColors)
    % Low-saturation blue-white-red map with a neutral midpoint.
    if nargin < 1
        nColors = 256;
    end

    blue = [49, 74, 125] / 255;
    white = [248, 248, 248] / 255;
    red = [165, 45, 45] / 255;

    nLower = floor(nColors / 2);
    nUpper = nColors - nLower;

    lower = [ ...
        linspace(blue(1), white(1), nLower).', ...
        linspace(blue(2), white(2), nLower).', ...
        linspace(blue(3), white(3), nLower).'];
    upper = [ ...
        linspace(white(1), red(1), nUpper).', ...
        linspace(white(2), red(2), nUpper).', ...
        linspace(white(3), red(3), nUpper).'];

    colorMap = [lower; upper];
end
